name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ejecuta el flujo de trabajo en cada push a la rama 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸ› ï¸
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install dependencies ğŸ“¦
        run: npm install

      - name: Build project ğŸ—ï¸
        run: npm run build # Este comando crearÃ¡ la carpeta 'dist'

      - name: Deploy to Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v4 # Action popular para Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Le indica que despliegue el contenido de la carpeta 'dist'
          force_orphan: true # Recomendado para limpiar la rama de despliegue anterior